### ISSUE TITLE
Semantic html tags

### ISSUE THREAD

**Issue by gegebe** [alecrem/almanac-remix#141]
Opening article
Opening div
h2 (day)
p (phrase)
Closing div
Closing article

Article, h2 and p instead of div. The div tag contained inside article is justifief by needs of design.

**Comment by alecrem** [comment]
Thank you, @gegebe!

I transferred your issue to the current repo.

**Comment by alecrem** [comment]
```html
<article>
  <div>
    <h2></h2>
    <p></p>
  </div>
</article>
```
